// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"time"
)

// AppointmentRow is the result of ListAppointments / GetAppointment (includes patient name).
type AppointmentRow struct {
	Appointment
	PatientNombre   *string `json:"patient_nombre"`
	PatientApellido *string `json:"patient_apellido"`
}

const listAppointments = `
SELECT a.id, a.doctor_id, a.patient_id, a.google_event_id, a.title,
       a.start_time, a.end_time, a.duration_minutes, a.status, a.notes,
       a.created_at, a.updated_at,
       p.nombre, p.apellido
FROM appointments a
LEFT JOIN patients p ON p.id = a.patient_id
WHERE a.doctor_id = $1
  AND a.start_time >= $2
  AND a.start_time <  $3
ORDER BY a.start_time ASC
`

// ListAppointments returns all appointments for a doctor within a time range.
func (q *Queries) ListAppointments(ctx context.Context, doctorID string, start, end time.Time) ([]AppointmentRow, error) {
	rows, err := q.db.Query(ctx, listAppointments, doctorID, start, end)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []AppointmentRow

	for rows.Next() {
		var r AppointmentRow

		if err := rows.Scan(
			&r.ID, &r.DoctorID, &r.PatientID, &r.GoogleEventID, &r.Title,
			&r.StartTime, &r.EndTime, &r.DurationMinutes, &r.Status, &r.Notes,
			&r.CreatedAt, &r.UpdatedAt,
			&r.PatientNombre, &r.PatientApellido,
		); err != nil {
			return nil, err
		}

		items = append(items, r)
	}

	return items, rows.Err()
}

const getAppointment = `
SELECT a.id, a.doctor_id, a.patient_id, a.google_event_id, a.title,
       a.start_time, a.end_time, a.duration_minutes, a.status, a.notes,
       a.created_at, a.updated_at,
       p.nombre, p.apellido
FROM appointments a
LEFT JOIN patients p ON p.id = a.patient_id
WHERE a.id = $1 AND a.doctor_id = $2
LIMIT 1
`

// GetAppointment fetches a single appointment by ID scoped to the doctor.
func (q *Queries) GetAppointment(ctx context.Context, id, doctorID string) (AppointmentRow, error) {
	row := q.db.QueryRow(ctx, getAppointment, id, doctorID)

	var r AppointmentRow

	err := row.Scan(
		&r.ID, &r.DoctorID, &r.PatientID, &r.GoogleEventID, &r.Title,
		&r.StartTime, &r.EndTime, &r.DurationMinutes, &r.Status, &r.Notes,
		&r.CreatedAt, &r.UpdatedAt,
		&r.PatientNombre, &r.PatientApellido,
	)

	return r, err
}

const createAppointment = `
INSERT INTO appointments (doctor_id, patient_id, google_event_id, title, start_time, end_time, duration_minutes, status, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, doctor_id, patient_id, google_event_id, title, start_time, end_time, duration_minutes, status, notes, created_at, updated_at
`

// CreateAppointmentParams holds the parameters for CreateAppointment.
type CreateAppointmentParams struct {
	DoctorID        string
	PatientID       *string
	GoogleEventID   *string
	Title           string
	StartTime       time.Time
	EndTime         time.Time
	DurationMinutes int
	Status          string
	Notes           *string
}

// CreateAppointment inserts a new appointment row.
func (q *Queries) CreateAppointment(ctx context.Context, p CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		p.DoctorID, p.PatientID, p.GoogleEventID, p.Title,
		p.StartTime, p.EndTime, p.DurationMinutes, p.Status, p.Notes,
	)

	var a Appointment

	err := row.Scan(
		&a.ID, &a.DoctorID, &a.PatientID, &a.GoogleEventID, &a.Title,
		&a.StartTime, &a.EndTime, &a.DurationMinutes, &a.Status, &a.Notes,
		&a.CreatedAt, &a.UpdatedAt,
	)

	return a, err
}

const updateAppointment = `
UPDATE appointments
SET title            = $3,
    patient_id       = $4,
    google_event_id  = $5,
    start_time       = $6,
    end_time         = $7,
    duration_minutes = $8,
    status           = $9,
    notes            = $10
WHERE id = $1 AND doctor_id = $2
RETURNING id, doctor_id, patient_id, google_event_id, title, start_time, end_time, duration_minutes, status, notes, created_at, updated_at
`

// UpdateAppointmentParams holds the parameters for UpdateAppointment.
type UpdateAppointmentParams struct {
	ID              string
	DoctorID        string
	Title           string
	PatientID       *string
	GoogleEventID   *string
	StartTime       time.Time
	EndTime         time.Time
	DurationMinutes int
	Status          string
	Notes           *string
}

// UpdateAppointment updates an existing appointment.
func (q *Queries) UpdateAppointment(ctx context.Context, p UpdateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, updateAppointment,
		p.ID, p.DoctorID, p.Title, p.PatientID, p.GoogleEventID,
		p.StartTime, p.EndTime, p.DurationMinutes, p.Status, p.Notes,
	)

	var a Appointment

	err := row.Scan(
		&a.ID, &a.DoctorID, &a.PatientID, &a.GoogleEventID, &a.Title,
		&a.StartTime, &a.EndTime, &a.DurationMinutes, &a.Status, &a.Notes,
		&a.CreatedAt, &a.UpdatedAt,
	)

	return a, err
}

const deleteAppointment = `DELETE FROM appointments WHERE id = $1 AND doctor_id = $2`

// DeleteAppointment removes an appointment.
func (q *Queries) DeleteAppointment(ctx context.Context, id, doctorID string) error {
	_, err := q.db.Exec(ctx, deleteAppointment, id, doctorID)
	return err
}

const countOverlapping = `
SELECT COUNT(*) FROM appointments
WHERE doctor_id = $1
  AND id != $2
  AND start_time < $4
  AND end_time   > $3
`

// CountOverlapping counts appointments overlapping a time range (excluding a given ID).
func (q *Queries) CountOverlapping(ctx context.Context, doctorID, excludeID string, start, end time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countOverlapping, doctorID, excludeID, start, end)

	var count int64

	return count, row.Scan(&count)
}
