// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// CreateEvolutionParams holds parameters for creating an evolution.
type CreateEvolutionParams struct {
	PatientID   string         `json:"patient_id"`
	DoctorID    string         `json:"doctor_id"`
	Descripcion string         `json:"descripcion"`
	Dientes     []int32        `json:"dientes"`
	Importe     pgtype.Numeric `json:"importe"`
	Pagado      bool           `json:"pagado"`
}

const createEvolution = `-- name: CreateEvolution :one
INSERT INTO evolutions (
    patient_id, doctor_id, descripcion, dientes, importe, pagado
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, patient_id, doctor_id, descripcion, dientes, importe, pagado, fecha, created_at`

// CreateEvolution inserts a new evolution record.
func (q *Queries) CreateEvolution(ctx context.Context, p CreateEvolutionParams) (Evolution, error) {
	row := q.db.QueryRow(ctx, createEvolution,
		p.PatientID, p.DoctorID, p.Descripcion, p.Dientes, p.Importe, p.Pagado,
	)
	var e Evolution
	err := row.Scan(
		&e.ID, &e.PatientID, &e.DoctorID, &e.Descripcion,
		&e.Dientes, &e.Importe, &e.Pagado, &e.Fecha, &e.CreatedAt,
	)
	return e, err
}

const listEvolutions = `-- name: ListEvolutions :many
SELECT id, patient_id, doctor_id, descripcion, dientes, importe, pagado, fecha, created_at
FROM evolutions
WHERE patient_id = $1 AND doctor_id = $2
ORDER BY fecha DESC`

// ListEvolutions returns all evolutions for a patient scoped to the doctor.
func (q *Queries) ListEvolutions(ctx context.Context, patientID, doctorID string) ([]Evolution, error) {
	rows, err := q.db.Query(ctx, listEvolutions, patientID, doctorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Evolution
	for rows.Next() {
		var e Evolution
		if err := rows.Scan(
			&e.ID, &e.PatientID, &e.DoctorID, &e.Descripcion,
			&e.Dientes, &e.Importe, &e.Pagado, &e.Fecha, &e.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, e)
	}
	return items, rows.Err()
}

// UpdateEvolutionParams holds parameters for updating an evolution.
type UpdateEvolutionParams struct {
	ID          string          `json:"id"`
	DoctorID    string          `json:"doctor_id"`
	Descripcion *string         `json:"descripcion"`
	Dientes     []int32         `json:"dientes"`
	Importe     *pgtype.Numeric `json:"importe"`
	Pagado      *bool           `json:"pagado"`
}

const updateEvolution = `-- name: UpdateEvolution :one
UPDATE evolutions SET
    descripcion = COALESCE($3, descripcion),
    dientes     = COALESCE($4, dientes),
    importe     = COALESCE($5, importe),
    pagado      = COALESCE($6, pagado)
WHERE id = $1 AND doctor_id = $2
RETURNING id, patient_id, doctor_id, descripcion, dientes, importe, pagado, fecha, created_at`

// UpdateEvolution updates an existing evolution record.
func (q *Queries) UpdateEvolution(ctx context.Context, p UpdateEvolutionParams) (Evolution, error) {
	row := q.db.QueryRow(ctx, updateEvolution,
		p.ID, p.DoctorID, p.Descripcion, p.Dientes, p.Importe, p.Pagado,
	)
	var e Evolution
	err := row.Scan(
		&e.ID, &e.PatientID, &e.DoctorID, &e.Descripcion,
		&e.Dientes, &e.Importe, &e.Pagado, &e.Fecha, &e.CreatedAt,
	)
	return e, err
}

// DeleteEvolution removes an evolution record.
func (q *Queries) DeleteEvolution(ctx context.Context, id, doctorID string) error {
	_, err := q.db.Exec(ctx,
		`DELETE FROM evolutions WHERE id = $1 AND doctor_id = $2`,
		id, doctorID,
	)
	return err
}
