// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// Patient represents a row in the patients table.
type Patient struct {
	ID              string           `json:"id"`
	DoctorID        string           `json:"doctor_id"`
	Nombre          string           `json:"nombre"`
	Apellido        string           `json:"apellido"`
	Dni             *string          `json:"dni"`
	FechaNacimiento *time.Time       `json:"fecha_nacimiento"`
	Sexo            *string          `json:"sexo"`
	Telefono        *string          `json:"telefono"`
	Email           *string          `json:"email"`
	Direccion       *string          `json:"direccion"`
	Alergias        *string          `json:"alergias"`
	Medicamentos    *string          `json:"medicamentos"`
	Antecedentes    *string          `json:"antecedentes"`
	ObraSocial      *string          `json:"obra_social"`
	NroAfiliado     *string          `json:"nro_afiliado"`
	Notas           *string          `json:"notas"`
	Odontograma     json.RawMessage  `json:"odontograma"`
	CreatedAt       time.Time        `json:"created_at"`
	UpdatedAt       time.Time        `json:"updated_at"`
}

// User represents a row in the users table.
type User struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Password  string    `json:"-"` // bcrypt hash — never serialised
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Evolution represents a row in the evolutions table.
type Evolution struct {
	ID          string          `json:"id"`
	PatientID   string          `json:"patient_id"`
	DoctorID    string          `json:"doctor_id"`
	Descripcion string          `json:"descripcion"`
	Dientes     []int32         `json:"dientes"`
	Importe     pgtype.Numeric  `json:"importe"`
	Pagado      bool            `json:"pagado"`
	Fecha       time.Time       `json:"fecha"`
	CreatedAt   time.Time       `json:"created_at"`
}
