// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"encoding/json"
	"time"
)

// ListPatientsRow is the result of the ListPatients query.
type ListPatientsRow struct {
	ID             string    `json:"id"`
	Nombre         string    `json:"nombre"`
	Apellido       string    `json:"apellido"`
	Dni            *string   `json:"dni"`
	Telefono       *string   `json:"telefono"`
	ObraSocial     *string   `json:"obra_social"`
	CreatedAt      time.Time `json:"created_at"`
	EvolutionCount int64     `json:"evolution_count"`
}

const listPatients = `-- name: ListPatients :many
SELECT
    id, nombre, apellido, dni, telefono, obra_social, created_at,
    (SELECT COUNT(*) FROM evolutions e WHERE e.patient_id = p.id) AS evolution_count
FROM patients p
WHERE doctor_id = $1
  AND (
    $2::text IS NULL
    OR nombre    ILIKE '%' || $2 || '%'
    OR apellido  ILIKE '%' || $2 || '%'
    OR dni       ILIKE '%' || $2 || '%'
  )
ORDER BY apellido ASC`

// ListPatients fetches all patients for a doctor with optional search filter.
func (q *Queries) ListPatients(ctx context.Context, doctorID string, query *string) ([]ListPatientsRow, error) {
	rows, err := q.db.Query(ctx, listPatients, doctorID, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []ListPatientsRow
	for rows.Next() {
		var i ListPatientsRow
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Apellido,
			&i.Dni,
			&i.Telefono,
			&i.ObraSocial,
			&i.CreatedAt,
			&i.EvolutionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getPatient = `-- name: GetPatient :one
SELECT id, doctor_id, nombre, apellido, dni, fecha_nacimiento, sexo,
       telefono, email, direccion, alergias, medicamentos,
       antecedentes, obra_social, nro_afiliado, notas, odontograma,
       created_at, updated_at
FROM patients
WHERE id = $1 AND doctor_id = $2
LIMIT 1`

// GetPatient fetches a single patient by ID scoped to the doctor.
func (q *Queries) GetPatient(ctx context.Context, id, doctorID string) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatient, id, doctorID)
	var p Patient
	err := row.Scan(
		&p.ID, &p.DoctorID, &p.Nombre, &p.Apellido, &p.Dni,
		&p.FechaNacimiento, &p.Sexo, &p.Telefono, &p.Email,
		&p.Direccion, &p.Alergias, &p.Medicamentos, &p.Antecedentes,
		&p.ObraSocial, &p.NroAfiliado, &p.Notas, &p.Odontograma,
		&p.CreatedAt, &p.UpdatedAt,
	)
	return p, err
}

// CreatePatientParams holds parameters for creating a patient.
type CreatePatientParams struct {
	DoctorID        string     `json:"doctor_id"`
	Nombre          string     `json:"nombre"`
	Apellido        string     `json:"apellido"`
	Dni             *string    `json:"dni"`
	FechaNacimiento *time.Time `json:"fecha_nacimiento"`
	Sexo            *string    `json:"sexo"`
	Telefono        *string    `json:"telefono"`
	Email           *string    `json:"email"`
	Direccion       *string    `json:"direccion"`
	Alergias        *string    `json:"alergias"`
	Medicamentos    *string    `json:"medicamentos"`
	Antecedentes    *string    `json:"antecedentes"`
	ObraSocial      *string    `json:"obra_social"`
	NroAfiliado     *string    `json:"nro_afiliado"`
	Notas           *string    `json:"notas"`
}

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (
    doctor_id, nombre, apellido, dni, fecha_nacimiento, sexo,
    telefono, email, direccion, alergias, medicamentos,
    antecedentes, obra_social, nro_afiliado, notas
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15
)
RETURNING id, doctor_id, nombre, apellido, dni, fecha_nacimiento, sexo,
          telefono, email, direccion, alergias, medicamentos,
          antecedentes, obra_social, nro_afiliado, notas, odontograma,
          created_at, updated_at`

// CreatePatient inserts a new patient record.
func (q *Queries) CreatePatient(ctx context.Context, p CreatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, createPatient,
		p.DoctorID, p.Nombre, p.Apellido, p.Dni, p.FechaNacimiento, p.Sexo,
		p.Telefono, p.Email, p.Direccion, p.Alergias, p.Medicamentos,
		p.Antecedentes, p.ObraSocial, p.NroAfiliado, p.Notas,
	)
	var out Patient
	err := row.Scan(
		&out.ID, &out.DoctorID, &out.Nombre, &out.Apellido, &out.Dni,
		&out.FechaNacimiento, &out.Sexo, &out.Telefono, &out.Email,
		&out.Direccion, &out.Alergias, &out.Medicamentos, &out.Antecedentes,
		&out.ObraSocial, &out.NroAfiliado, &out.Notas, &out.Odontograma,
		&out.CreatedAt, &out.UpdatedAt,
	)
	return out, err
}

// UpdatePatientParams holds parameters for updating a patient.
type UpdatePatientParams struct {
	ID              string     `json:"id"`
	DoctorID        string     `json:"doctor_id"`
	Nombre          *string    `json:"nombre"`
	Apellido        *string    `json:"apellido"`
	Dni             *string    `json:"dni"`
	FechaNacimiento *time.Time `json:"fecha_nacimiento"`
	Sexo            *string    `json:"sexo"`
	Telefono        *string    `json:"telefono"`
	Email           *string    `json:"email"`
	Direccion       *string    `json:"direccion"`
	Alergias        *string    `json:"alergias"`
	Medicamentos    *string    `json:"medicamentos"`
	Antecedentes    *string    `json:"antecedentes"`
	ObraSocial      *string    `json:"obra_social"`
	NroAfiliado     *string    `json:"nro_afiliado"`
	Notas           *string    `json:"notas"`
}

const updatePatient = `-- name: UpdatePatient :one
UPDATE patients SET
    nombre           = COALESCE($3,  nombre),
    apellido         = COALESCE($4,  apellido),
    dni              = COALESCE($5,  dni),
    fecha_nacimiento = COALESCE($6,  fecha_nacimiento),
    sexo             = COALESCE($7,  sexo),
    telefono         = COALESCE($8,  telefono),
    email            = COALESCE($9,  email),
    direccion        = COALESCE($10, direccion),
    alergias         = COALESCE($11, alergias),
    medicamentos     = COALESCE($12, medicamentos),
    antecedentes     = COALESCE($13, antecedentes),
    obra_social      = COALESCE($14, obra_social),
    nro_afiliado     = COALESCE($15, nro_afiliado),
    notas            = COALESCE($16, notas)
WHERE id = $1 AND doctor_id = $2
RETURNING id, doctor_id, nombre, apellido, dni, fecha_nacimiento, sexo,
          telefono, email, direccion, alergias, medicamentos,
          antecedentes, obra_social, nro_afiliado, notas, odontograma,
          created_at, updated_at`

// UpdatePatient updates an existing patient's fields (nil = keep existing).
func (q *Queries) UpdatePatient(ctx context.Context, p UpdatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, updatePatient,
		p.ID, p.DoctorID,
		p.Nombre, p.Apellido, p.Dni, p.FechaNacimiento, p.Sexo,
		p.Telefono, p.Email, p.Direccion, p.Alergias, p.Medicamentos,
		p.Antecedentes, p.ObraSocial, p.NroAfiliado, p.Notas,
	)
	var out Patient
	err := row.Scan(
		&out.ID, &out.DoctorID, &out.Nombre, &out.Apellido, &out.Dni,
		&out.FechaNacimiento, &out.Sexo, &out.Telefono, &out.Email,
		&out.Direccion, &out.Alergias, &out.Medicamentos, &out.Antecedentes,
		&out.ObraSocial, &out.NroAfiliado, &out.Notas, &out.Odontograma,
		&out.CreatedAt, &out.UpdatedAt,
	)
	return out, err
}

// DeletePatient removes a patient scoped to the doctor.
func (q *Queries) DeletePatient(ctx context.Context, id, doctorID string) error {
	_, err := q.db.Exec(ctx,
		`DELETE FROM patients WHERE id = $1 AND doctor_id = $2`,
		id, doctorID,
	)
	return err
}

// SaveOdontogramRow is returned after saving an odontogram.
type SaveOdontogramRow struct {
	ID          string          `json:"id"`
	Odontograma json.RawMessage `json:"odontograma"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

// SaveOdontogram persists the odontogram JSON for a patient.
func (q *Queries) SaveOdontogram(ctx context.Context, id, doctorID string, data json.RawMessage) (SaveOdontogramRow, error) {
	row := q.db.QueryRow(ctx,
		`UPDATE patients SET odontograma = $3
         WHERE id = $1 AND doctor_id = $2
         RETURNING id, odontograma, updated_at`,
		id, doctorID, data,
	)
	var out SaveOdontogramRow
	err := row.Scan(&out.ID, &out.Odontograma, &out.UpdatedAt)
	return out, err
}
