// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"time"
)

const getUserSettings = `
SELECT doctor_id, timezone, doctor_name, clinic_address, clinic_phone, email_language, created_at, updated_at
FROM user_settings WHERE doctor_id = $1 LIMIT 1
`

// GetUserSettings fetches settings for a doctor, returning ErrNoRows if not found.
func (q *Queries) GetUserSettings(ctx context.Context, doctorID string) (UserSettings, error) {
	row := q.db.QueryRow(ctx, getUserSettings, doctorID)

	var s UserSettings

	err := row.Scan(
		&s.DoctorID, &s.Timezone,
		&s.DoctorName, &s.ClinicAddress, &s.ClinicPhone, &s.EmailLanguage,
		&s.CreatedAt, &s.UpdatedAt,
	)

	return s, err
}

const upsertUserSettings = `
INSERT INTO user_settings (doctor_id, timezone, doctor_name, clinic_address, clinic_phone, email_language)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (doctor_id) DO UPDATE SET
    timezone       = EXCLUDED.timezone,
    doctor_name    = EXCLUDED.doctor_name,
    clinic_address = EXCLUDED.clinic_address,
    clinic_phone   = EXCLUDED.clinic_phone,
    email_language = EXCLUDED.email_language
RETURNING doctor_id, timezone, doctor_name, clinic_address, clinic_phone, email_language, created_at, updated_at
`

// UpsertUserSettingsParams holds the parameters for UpsertUserSettings.
type UpsertUserSettingsParams struct {
	DoctorID      string
	Timezone      string
	DoctorName    string
	ClinicAddress string
	ClinicPhone   string
	EmailLanguage string
}

// UpsertUserSettings creates or updates user settings.
func (q *Queries) UpsertUserSettings(ctx context.Context, p UpsertUserSettingsParams) (UserSettings, error) {
	row := q.db.QueryRow(ctx, upsertUserSettings,
		p.DoctorID, p.Timezone, p.DoctorName, p.ClinicAddress, p.ClinicPhone, p.EmailLanguage,
	)

	var s UserSettings

	err := row.Scan(
		&s.DoctorID, &s.Timezone,
		&s.DoctorName, &s.ClinicAddress, &s.ClinicPhone, &s.EmailLanguage,
		&s.CreatedAt, &s.UpdatedAt,
	)

	return s, err
}

const getGoogleToken = `
SELECT id, doctor_id, access_token, refresh_token, expiry, calendar_id, created_at, updated_at
FROM google_tokens WHERE doctor_id = $1 LIMIT 1
`

// GetGoogleToken fetches the stored Google OAuth token for a doctor.
func (q *Queries) GetGoogleToken(ctx context.Context, doctorID string) (GoogleToken, error) {
	row := q.db.QueryRow(ctx, getGoogleToken, doctorID)

	var t GoogleToken

	err := row.Scan(
		&t.ID, &t.DoctorID, &t.AccessToken, &t.RefreshToken,
		&t.Expiry, &t.CalendarID, &t.CreatedAt, &t.UpdatedAt,
	)

	return t, err
}

const upsertGoogleToken = `
INSERT INTO google_tokens (doctor_id, access_token, refresh_token, expiry, calendar_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (doctor_id) DO UPDATE
SET access_token  = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    expiry        = EXCLUDED.expiry,
    calendar_id   = EXCLUDED.calendar_id
RETURNING id, doctor_id, access_token, refresh_token, expiry, calendar_id, created_at, updated_at
`

// UpsertGoogleTokenParams holds the parameters for UpsertGoogleToken.
type UpsertGoogleTokenParams struct {
	DoctorID     string
	AccessToken  string
	RefreshToken string
	Expiry       time.Time
	CalendarID   string
}

// UpsertGoogleToken stores or refreshes a doctor's Google OAuth token.
func (q *Queries) UpsertGoogleToken(ctx context.Context, p UpsertGoogleTokenParams) (GoogleToken, error) {
	row := q.db.QueryRow(ctx, upsertGoogleToken,
		p.DoctorID, p.AccessToken, p.RefreshToken, p.Expiry, p.CalendarID,
	)

	var t GoogleToken

	err := row.Scan(
		&t.ID, &t.DoctorID, &t.AccessToken, &t.RefreshToken,
		&t.Expiry, &t.CalendarID, &t.CreatedAt, &t.UpdatedAt,
	)

	return t, err
}

const deleteGoogleToken = `DELETE FROM google_tokens WHERE doctor_id = $1`

// DeleteGoogleToken removes a doctor's Google Calendar connection.
func (q *Queries) DeleteGoogleToken(ctx context.Context, doctorID string) error {
	_, err := q.db.Exec(ctx, deleteGoogleToken, doctorID)
	return err
}
