// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

const createUser = `
INSERT INTO users (email, name, password)
VALUES ($1, $2, $3)
RETURNING id, email, name, password, created_at, updated_at
`

// CreateUser inserts a new user and returns the created row.
func (q *Queries) CreateUser(ctx context.Context, email, name, password string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, email, name, password)

	var u User

	err := row.Scan(&u.ID, &u.Email, &u.Name, &u.Password, &u.CreatedAt, &u.UpdatedAt)

	return u, err
}

const getUserByEmail = `
SELECT id, email, name, password, created_at, updated_at
FROM users
WHERE email = $1
LIMIT 1
`

// GetUserByEmail fetches a user by email address.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)

	var u User

	err := row.Scan(&u.ID, &u.Email, &u.Name, &u.Password, &u.CreatedAt, &u.UpdatedAt)

	return u, err
}

const getUserByID = `
SELECT id, email, name, password, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

// GetUserByID fetches a user by their UUID.
func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)

	var u User

	err := row.Scan(&u.ID, &u.Email, &u.Name, &u.Password, &u.CreatedAt, &u.UpdatedAt)

	return u, err
}
