ALTER TABLE user_settings
    ADD COLUMN IF NOT EXISTS doctor_name    TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS clinic_address TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS clinic_phone   TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS email_language TEXT NOT NULL DEFAULT 'es';
